services:
  postgres:
    image: postgres:13
    container_name: opiniones_postgres
    environment:
      POSTGRES_USER: IN6AV
      POSTGRES_PASSWORD: In6avKnl!
      POSTGRES_DB: gestor_opiniones
    ports:
      - "5436:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data: